language: minimal
sudo: false
services:
  - docker

cache:
  directories:
    - _build
env:
  - TOOL=ruby VERSION=2.4.2

install:
  - pip install --user awscli

script:
  - make tool-available || make tool
  - make test
