language: minimal
sudo: false
services:
  - docker

cache:
  directories:
    - _build
env:
  - TOOL=elixir VERSION=1.5.0-otp-20
  - TOOL=elixir VERSION=1.5.1-otp-20
  - TOOL=elixir VERSION=1.5.2-otp-20

install:
  - make builder
  - pip install --user awscli

script:
  - make tool-available || make tool
