language: minimal
sudo: false
services:
  - docker

cache:
  directories:
    - _build
env:
  - TOOL=ruby VERSION=2.4.2
  - TOOL=ruby VERSION=2.0.0-p648
  - TOOL=ruby VERSION=2.1.10
  - TOOL=ruby VERSION=2.2.8
  - TOOL=ruby VERSION=2.3.5
  - TOOL=ruby VERSION=2.4.0
  - TOOL=ruby VERSION=2.4.1
  - TOOL=ruby VERSION=2.4.2

install:
  - pip install --user awscli

script:
  - make tool-available || make tool
  - make test
