language: generic
sudo: false
services:
  - docker

cache:
  directories:
    - _build
env:
  - TOOL=elixir VERSION=1.5.0-otp-20
  - TOOL=elixir VERSION=1.5.1-otp-20
  - TOOL=elixir VERSION=1.5.2-otp-20

install:
  - make builder

script:
  - make tool-build tool-package

addons:
  artifacts:
    debug: true
    paths:
      - "_build/$TOOL/$VERSION.tgz"
