language: minimal
sudo: false
services:
  - docker

cache:
  directories:
    - _build
env:
  # - TOOL=erlang VERSION=17.0
  # - TOOL=erlang VERSION=17.1
  # - TOOL=erlang VERSION=17.3
  # - TOOL=erlang VERSION=17.4
  # - TOOL=erlang VERSION=17.5
  # - TOOL=erlang VERSION=18.0
  # - TOOL=erlang VERSION=18.1
  - TOOL=erlang VERSION=18.2.1
  - TOOL=erlang VERSION=18.3
  - TOOL=erlang VERSION=19.0
  - TOOL=erlang VERSION=19.1
  - TOOL=erlang VERSION=19.2
  - TOOL=erlang VERSION=19.3
  - TOOL=erlang VERSION=20.0
  - TOOL=erlang VERSION=20.1

  - TOOL=elixir VERSION=1.3.0
  - TOOL=elixir VERSION=1.3.1
  - TOOL=elixir VERSION=1.3.2
  - TOOL=elixir VERSION=1.3.3
  - TOOL=elixir VERSION=1.3.4
  - TOOL=elixir VERSION=1.4.0
  - TOOL=elixir VERSION=1.4.1
  - TOOL=elixir VERSION=1.4.2
  - TOOL=elixir VERSION=1.4.3
  - TOOL=elixir VERSION=1.4.4
  - TOOL=elixir VERSION=1.4.5
  - TOOL=elixir VERSION=1.5.0-otp-20
  - TOOL=elixir VERSION=1.5.0-otp-20
  - TOOL=elixir VERSION=1.5.1-otp-20
  - TOOL=elixir VERSION=1.5.2-otp-20

  - TOOL=nodejs VERSION=7.9.0
  - TOOL=nodejs VERSION=7.10.1
  - TOOL=nodejs VERSION=8.8.1
  - TOOL=nodejs VERSION=8.9.1
  - TOOL=nodejs VERSION=9.2.0

install:
  - pip install --user awscli

script:
  - make tool-available || make tool
  - make test
